//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPremier
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRequest
    {
        public int RequestId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Explanation { get; set; }
        public int WorkerId { get; set; }
        public int ManagerId { get; set; }
        public bool Mgn { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
    }
}
