//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPremier
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWorker
    {
        public int HotelUserId { get; set; }
        public string FullName { get; set; }
        public int IDNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public int WorkerId { get; set; }
        public int ClinicFloor { get; set; }
        public string Citizenship { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int GenderId { get; set; }
        public int EngagmentId { get; set; }
        public int Expr1 { get; set; }
    }
}
